name: GitHub Actions - Push Template Basic
run-name: Runnig - ${{ github.event_name }}
on: 
  push:
    branches-ignore:       
      - develop

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: | 
          echo "Branches ignore on push"