name: GitHub Actions - On Pull Request Types
run-name: Runnig - ${{ github.event_name }}
on: 
  pull_request:
    types:
      - opened
      - reopened
      - closed

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: | 
          echo "path on push"