name: GitHub Actions - On Pull Request Branch
run-name: Runnig - ${{ github.event_name }}
on: 
  pull_request:
    branches:
      "main"

jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: | 
          echo "path on push"